# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cyrillizer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dalibor Nasevic"]
  s.date = %q{2010-05-23}
  s.description = %q{Character conversion from latin alphabet to Macedonian cyrillic alphabet and vice versa}
  s.email = %q{dalibor.nasevic@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/convert_latin_to_cyrillic.feature",
     "features/step_definitions/convert_latin_to_cyrillic_steps.rb",
     "features/support/env.rb",
     "lib/cyrillizer.rb",
     "lib/cyrillizer/converter.rb",
     "spec/cyrillizer_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dalibor/cyrillizer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Character conversion from latin alphabet to Macedonian cyrillic alphabet and vice versa}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/cyrillizer_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

